version: "3.8"
services:
  postgres:
    image: postgres:11.13-alpine
    working_dir: /app
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: pg_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - .:/app
  nodejs:
    image: node:14-alpine
    depends_on:
      postgres:
        condition: service_healthy
    command: tail -F anything
    working_dir: /app
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: pg_test
    volumes:
      - .:/app