name: Test Lambdas

on: [push]

jobs:
  test-add-person:
    uses: weberlo1/reusable_workflows/.github/workflows/test_sql.yaml@dev
    with:
      pathname: ./functions/add_person
  
  test-delete-person:
    uses: weberlo1/reusable_workflows/.github/workflows/test_sql.yaml@dev
    with:
      pathname: ./functions/delete_person

  test-find-person:
    uses: weberlo1/reusable_workflows/.github/workflows/test_sql.yaml@dev
    with:
      pathname: ./functions/find_person

  test-get-person:
    uses: weberlo1/reusable_workflows/.github/workflows/test_sql.yaml@dev
    with:
      pathname: ./functions/get_person

  test-list-person:
    uses: weberlo1/reusable_workflows/.github/workflows/test_sql.yaml@dev
    with:
      pathname: ./functions/list_person