name: Test Lambdas

on: [push]

jobs:
  test-add-person:
    uses: weberlo1/reusable_workflows/.github/workflows/test_sql.yaml@dev
    with:
      pathname: ./code_add_person
  
  test-delete-person:
    uses: weberlo1/reusable_workflows/.github/workflows/test_sql.yaml@dev
    with:
      pathname: ./code_delete_person
