name: PostgreSQL Test

on: [push]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:14


    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Install dependencies
      working-directory: ./code_add_person
      run: npm install

    # - name: Set environment variable
    #   run: echo "TEST_DATABASE_URL=postgres://postgres:postgres@localhost:5432/test_db" >> $GITHUB_ENV

    - name: Setup PG cli
      run: |
        apt-get update
        apt-get install --yes --no-install-recommends postgresql-client
      
    - name: Enable uuid-ossp extension
      run: |
        PGPASSWORD=postgres psql -U postgres -h postgres -d test_db -c 'CREATE EXTENSION "uuid-ossp";'

    # - name: Load SQL script
    #   run: |
    #     PGPASSWORD=postgres psql -U postgres -h postgres -d test_db -f sql/person.sql
    - name: Run tests
      working-directory: ./code_add_person
      run: npx jest
